In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
torch.__version__

'2.7.0+cu126'

# Tensors 

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [10]:
Mat = torch.tensor([[ 7,8],
                   [9,10]])
Mat

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
Mat.ndim

2

In [16]:
Mat[-2]

tensor([7, 8])

In [17]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [18]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
tensor.shape

torch.Size([1, 3, 3])